### ISSUE TITLE
Warnings disappearing 

### ISSUE THREAD

**Issue by AntoineDarveau** [AntoineDarveau/exofile#31]
When running in the jupyter notebook example, each warning shows only once.

**Comment by vandalt** [comment]
In the master branch ? If you re-run the same cell twice warnings should indeed show only once I think (see last sentence of 3rd paragraph here: https://docs.python.org/3/library/warnings.html)

**Comment by vandalt** [comment]
Closing as this is the expected behaviour

For example, this warns only once:

```python
import warnings

for i in range(10):
    warnings.warn("WARNING FROM THOMAS", RuntimeWarning)
```
