### ISSUE TITLE
Astroquery requirement

### ISSUE THREAD

**Issue by boucherastro** [AntoineDarveau/exofile#41]
When installing the exofile, it passed all requirements, but when it was time to use it, I got an error saying that astroquery.ipac did not exist. I updated my astroquery version to 0.4.6 (previously at 0.4.3) and it worked.

**Comment by vandalt** [comment]
Hi @boucherastro, just to be sure, was this in an environment where astroquery was already installed (or cached somewhere)? I did not know that older versions did not have the `ipac` module. According to [this](https://github.com/astropy/astroquery/blob/main/CHANGES.rst#044-2021-11-17=) it was added in 0.4.4. I'll update the requirement to specifcy `astroquery >= 0.4.4`. Thank you!
